{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.story(\"失败功能\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.testcase(\"失败链接\",'www.baidu.com')\n    def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:16: AssertionError"}, "description": "this test fails", "start": 1659526070688, "stop": 1659526070688, "uuid": "f3e36975-551f-46ea-a8eb-6f32ee506ba6", "historyId": "b2873979f94e50b7249573af844598f1", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "story", "value": "失败功能"}, {"name": "severity", "value": "normal"}, {"name": "suite", "value": "test_allure"}, {"name": "host", "value": "yin"}, {"name": "thread", "value": "18128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}], "links": [{"type": "test_case", "url": "失败链接", "name": "www.baidu.com"}]}