{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@allure.story(\"失败功能\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @allure.testcase('www.baidu.com','百度')\n    def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_allure.py:16: AssertionError"}, "description": "this test fails", "start": 1659526563137, "stop": 1659526563137, "uuid": "e78f9483-a4ce-4e7c-9b64-300dc3f5825a", "historyId": "b2873979f94e50b7249573af844598f1", "testCaseId": "924c4ecc2b1e866f13aa32d5ad57625b", "fullName": "test_allure#test_failure", "labels": [{"name": "severity", "value": "normal"}, {"name": "story", "value": "失败功能"}, {"name": "suite", "value": "test_allure"}, {"name": "host", "value": "yin"}, {"name": "thread", "value": "39608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure"}], "links": [{"type": "test_case", "url": "www.baidu.com", "name": "百度"}]}